### PR TITLE
Castle tests

### PR DESCRIPTION
**Pull request by snuchhi**
castle tests for utility functions.. Will add more castle tests once this is merged to avoid any merge conflicts

### CODE REVIEW

**Review by thePurpleMonkey — APPROVED** [review]

**Review by JasonLarson44 — APPROVED** [review]

**Review by JasonLarson44 — COMMENTED** [review]
Looks good.

**Comment by JasonLarson44** [comment]
Thanks for adding tests around the combat functions

**Comment by JasonLarson44** [comment]
I fixed the merge conflicts caused by my test branch getting merged before this

**Comment by JasonLarson44** [comment]
I had to replace a call to self.log with utilities.log to fix the tests.

**Pull request merged**
